import React,{useEffect,useRef,useState} from 'react';
import {Sun,Cpu,Folder,Settings,Monitor,Link,Save,Play,Pause,RefreshCw,ArrowRightLeft,Rainbow,Activity,Waves,Sparkles,Blend,Check,ChevronRight,X,Plus,Trash2,Download,Upload,Search,Power,SlidersHorizontal,ExternalLink,Info,CheckCircle2,Keyboard,Mouse,Headphones,Gamepad2,Lightbulb,Usb,HardDrive,Mic,Gauge,Flame,Orbit,ScanLine} from 'lucide-react';
import {PCPreview,DeviceVisual} from './PCPreview.jsx';
import {SystemInventory} from './SystemInventory.jsx';
import {RGBDiscovery,ControllerChannels,providerName} from './RGBDiscovery.jsx';
import {ManufacturerCoverage} from './ManufacturerCoverage.jsx';
import {DEFAULT_CONFIG,PREVIEW_DEVICES,SCENES,EFFECT_NAMES,EFFECT_DETAILS,MAX_PROFILES,api,categorize,readProfiles,validConfig,downloadProfiles,hexToHsv,hsvToHex} from './data.js';

const NAV=[['lighting','Beleuchtung',Sun],['devices','Geräte',Cpu],['profiles','Profile',Folder],['settings','Einstellungen',Settings]];
function coverageStatusSignature(value){return JSON.stringify({connected:value.connected,deviceCount:value.deviceCount,native:value.native,error:value.error});}
function inactiveCoverage(value){if(!value)return value;return {...value,brands:(value.brands||[]).map(brand=>brand.status==='controllable'||brand.controlledNames?.length?{...brand,status:brand.status==='excluded'?'excluded':'detected',controlledNames:[],integration:brand.integration?.status==='ready'?{...brand.integration,status:'disconnected',message:'Aktuell ist keine aktive RGB-Verbindung bestätigt. Die zuletzt erfassten Gerätenamen bleiben sichtbar.'}:brand.integration}:brand),providers:(value.providers||[]).map(provider=>['windows','corsair'].includes(provider.id)&&provider.status!=='sdkMissing'?{...provider,status:'disconnected',deviceCount:0,message:'Aktuell ist keine aktive RGB-Verbindung bestätigt. Erfasste Gerätenamen bleiben sichtbar.'}:provider)};}
function WaveIcon({size=27}){return <svg width={size} height={size} viewBox="0 0 28 28" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" aria-hidden="true"><path d="M2 17c5-13 8-13 12-5s7 8 12-3"/></svg>}
function GradientIcon({size=27}){return <svg width={size} height={size} viewBox="0 0 28 28" aria-hidden="true"><rect x="2" y="10" width="16" height="8" rx="4" fill="currentColor" opacity=".45"/><rect x="11" y="10" width="15" height="8" rx="4" fill="currentColor"/></svg>}
const EFFECT_ICONS={static:Sun,rainbow:Rainbow,breathing:Activity,wave:WaveIcon,gradient:GradientIcon,sparkle:Sparkles,colorcycle:ArrowRightLeft,comet:Orbit,chase:ChevronRight,scanner:ScanLine,ripple:Waves,fire:Flame,aurora:WaveIcon,stripes:Blend};
function PrismLogo(){return <svg viewBox="0 0 40 48" aria-hidden="true"><path d="M20 2 38 31 20 46 2 31Z M20 2V46 M2 31 20 26 38 31" fill="none" stroke="currentColor" strokeWidth="1.8"/></svg>}
function HardwareVisual({type}){const Icon={keyboard:Keyboard,mouse:Mouse,headset:Headphones,gamepad:Gamepad2,light:Lightbulb,peripheral:Usb,drive:HardDrive,microphone:Mic}[type];return Icon?<div className="device-visual peripheral-visual"><Icon size={49} strokeWidth={1.4}/></div>:<DeviceVisual type={type}/>}
function Modal({title,children,onClose}){const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('input,button')?.focus();const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const list=[...ref.current.querySelectorAll('button,input,a,select,[tabindex="0"]')].filter(x=>!x.disabled);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal" role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Schließen"><X size={20}/></button></div>{children}</section></div>}
function ColorPicker({colors,onChange,singleColor=false}){
 const [active,setActive]=useState(0),[hex,setHex]=useState(colors[0]);
 const index=singleColor?0:Math.min(active,colors.length-1),color=colors[index],hsv=hexToHsv(color);
 useEffect(()=>setHex(color),[color]);
 function setColor(value){const next=[...colors];next[index]=value;onChange(next);}
 function choose(e){const r=e.currentTarget.getBoundingClientRect();setColor(hsvToHex(hsv.h,Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))));}
 return <div className="color-editor"><h3>{singleColor?'Farbe':'Farben'}</h3><div className="swatch-row">{(singleColor?colors.slice(0,1):colors).map((value,i)=><button key={i} className={`swatch ${index===i?'selected':''}`} style={{background:value}} aria-label={`Farbe ${i+1} bearbeiten`} aria-pressed={index===i} onClick={()=>setActive(i)}/>)}{!singleColor&&colors.length<8?<button className="add-color" aria-label="Farbe hinzufügen" onClick={()=>{onChange([...colors,'#ffffff']);setActive(colors.length);}}><Plus size={16}/></button>:null}{!singleColor&&colors.length>1?<button className="add-color" aria-label="Aktuelle Farbe entfernen" onClick={()=>{onChange(colors.filter((_,i)=>i!==index));setActive(0);}}><X size={14}/></button>:null}</div><div className="picker-row"><div className="color-field" style={{backgroundColor:`hsl(${hsv.h},100%,50%)`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);choose(e);}} onPointerMove={e=>{if(e.buttons===1)choose(e);}} role="slider" tabIndex={0} aria-label="Sättigung und Helligkeit der Farbe" aria-valuetext={color} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setColor(hsvToHex(hsv.h,Math.max(0,Math.min(1,hsv.s+(e.key==='ArrowRight'?.02:e.key==='ArrowLeft'?-.02:0))),Math.max(0,Math.min(1,hsv.v+(e.key==='ArrowUp'?.02:e.key==='ArrowDown'?-.02:0)))));}}}><span className="color-cursor" style={{left:`${hsv.s*100}%`,top:`${(1-hsv.v)*100}%`}}/></div><input className="hue-slider" type="range" min="0" max="359" value={Math.round(hsv.h)} aria-label="Farbton" onChange={e=>setColor(hsvToHex(+e.target.value,hsv.s,hsv.v))}/></div><div className="hex-row"><input aria-label="Hex-Farbcode" value={hex.toUpperCase()} maxLength={7} onChange={e=>{setHex(e.target.value);if(/^#[\da-f]{6}$/i.test(e.target.value))setColor(e.target.value);}} onBlur={()=>{if(!/^#[\da-f]{6}$/i.test(hex))setHex(color);}}/><label className="native-color" aria-label="System-Farbwähler öffnen"><SlidersHorizontal size={18}/><input type="color" value={color} onChange={e=>setColor(e.target.value)} aria-label="System-Farbwähler"/></label></div></div>;
}
function Slider({icon:Icon,label,value,onChange,min=0}){return <label className="slider-control"><span><Icon size={19}/>{label}<output>{value}%</output></span><input type="range" aria-label={label} min={min} max="100" value={value} onChange={e=>onChange(+e.target.value)} style={{'--progress':`${value}%`}}/></label>}
function EffectEditor({config,setConfig,onApply,onPreviewStart,busy,preview,selectedCount}){
 const change=(key,value)=>{setConfig(c=>({...c,[key]:value}));if(key==='effect')onPreviewStart?.();},details=EFFECT_DETAILS[config.effect]||EFFECT_DETAILS.static;
 return <aside className="inspector surface">
  <div className="effect-heading"><h3>Effekt</h3><span>{Object.keys(EFFECT_NAMES).length} Effekte</span></div>
  <div className="effect-grid">{Object.entries(EFFECT_NAMES).map(([key,name])=>{const Icon=EFFECT_ICONS[key]||Sparkles;return <button key={key} className={`effect-tile ${config.effect===key?'active':''}`} aria-label={name} aria-pressed={config.effect===key} onClick={()=>change('effect',key)}><Icon size={24} aria-hidden="true"/><span>{name}</span></button>;})}</div>
  <div className="effect-description"><strong>{EFFECT_NAMES[config.effect]}</strong><p>{details.description}</p></div>
  {details.colors==='spectrum'?<p className="effect-color-note">Regenbogen nutzt automatische Spektrumfarben.</p>:<ColorPicker colors={config.colors} singleColor={details.colors==='first'} onChange={value=>change('colors',value)}/>}
  {details.note?<p className="effect-color-note">{details.note}</p>:null}
  <Slider icon={Sun} label="Helligkeit" value={config.brightness} onChange={v=>change('brightness',v)}/>
  {details.speed?<Slider icon={Gauge} label="Geschwindigkeit" value={config.speed} min={1} onChange={v=>change('speed',v)}/>:null}
  {details.direction?<div className="direction"><label><ArrowRightLeft size={20}/>{details.directionLabel||'Richtung'}</label><div className="segmented">{[['forward','Vorwärts'],['reverse','Rückwärts']].map(([v,label])=><button key={v} className={config.direction===v?'active':''} onClick={()=>change('direction',v)} aria-pressed={config.direction===v}>{label}</button>)}</div></div>:null}
  {details.scale?<details className="more-options"><summary>Feineinstellungen <ChevronRight size={14}/></summary><Slider icon={Waves} label={details.scale.label} value={config.scale} min={1} onChange={v=>change('scale',v)}/><p>{details.scale.help}</p></details>:null}
  <button className="primary apply-button" onClick={onApply} disabled={busy||selectedCount===0}><Play size={18} fill="currentColor"/>{busy?'Wird angewendet …':'Auf Geräte anwenden'}</button><p className="inspector-note">{preview?'Vorschaumodus · Änderungen bleiben virtuell.':'Änderungen zuerst in der Vorschau. Mit „Auf Geräte anwenden“ änderst du das Licht.'}</p>
 </aside>;
}
function Scenes({onChoose,active}){return <section className="scenes surface"><h3>Szenen</h3><div className="scene-row">{SCENES.map(scene=><button className={`scene ${active===scene.name?'active':''}`} key={scene.name} aria-label={scene.name} aria-pressed={active===scene.name} onClick={()=>onChoose(scene)}><div className="scene-art" style={{'--c1':scene.colors[0],'--c2':scene.colors[1],'--c3':scene.colors[2]}}><svg viewBox="0 0 240 64" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id={`g-${scene.name.replaceAll(' ','')}`}><stop stopColor={scene.colors[0]}/><stop offset=".5" stopColor={scene.colors[1]}/><stop offset="1" stopColor={scene.colors[2]}/></linearGradient></defs><path d="M-10 46 Q35 0 86 36T175 35T260 27" fill="none" stroke={`url(#g-${scene.name.replaceAll(' ', '')})`} strokeWidth="2.5"/><path d="M-10 43 Q35 15 86 38T175 36T260 33" fill="none" stroke={`url(#g-${scene.name.replaceAll(' ', '')})`} strokeWidth="11" opacity=".2"/></svg></div><span>{scene.name}<small>{EFFECT_NAMES[scene.effect]}</small></span></button>)}</div></section>}
function DeviceSelector({devices,selected,onToggle,preview}){return <div className="device-selectors">{devices.map(d=><button key={d.id} className={`device-selector ${selected.includes(d.id)?'selected':''}`} disabled={!preview&&!d.directMode} onClick={()=>onToggle(d.id)} aria-pressed={selected.includes(d.id)}><span className="device-label"><span className="checkbox">{selected.includes(d.id)?<Check size={13}/>:null}</span><span title={d.name}>{d.name}</span></span><HardwareVisual type={d.category}/><span className="device-meta">{preview?'Vorschau':d.directMode?`${d.ledCount} LEDs`:'Nicht steuerbar'}</span></button>)}</div>}
function ConnectionDialog({status,busy,onConnect,onSetup,onShowWindow,onClose,corsair}){
 const [acceptLicense,setAcceptLicense]=useState(false);
 const native=status.native||{};
 return <Modal title="RGB ohne OpenRGB" onClose={onClose}>
  <p>PRISM sucht nach Geräten mit Windows-RGB-Unterstützung und nach Corsair-Geräten über iCUE. PC-Komponenten können erkannt sein, auch wenn ihre LEDs keine dieser Schnittstellen unterstützen.</p>
  <section className="connection-provider"><h3>Windows · Dynamische Beleuchtung</h3><p>Für kompatible Geräte mit LampArray-Unterstützung. Mainboard- und RAM-Beleuchtung wird von dieser Windows-Schnittstelle häufig nicht bereitgestellt.</p><p className="small">Für diese Geräte muss das PRISM-Steuerfenster im Vordergrund bleiben. Eine andere Beleuchtungs-App kann die Steuerung belegen.</p>{native.windows?.message?<p className="provider-status">{native.windows.message}</p>:null}{native.windows?.deviceCount>0?<button className="secondary wide" onClick={onShowWindow} disabled={busy}><Monitor size={17}/>PRISM-Steuerfenster nach vorne holen</button>:null}</section>
  <section className="connection-provider"><h3>Corsair-Geräte</h3><p>Öffne iCUE und erlaube dort die SDK-Steuerung. PRISM kann dann unterstützte Corsair-Geräte direkt ansprechen, beispielsweise RGB-Arbeitsspeicher.</p>{native.corsair?.message?<p className="provider-status">{native.corsair.message}</p>:null}{corsair?.sdkInstalled?<p className="support-status">Corsair-Anbindung ist eingerichtet.</p>:<><label className="license-consent"><input type="checkbox" checked={acceptLicense} onChange={e=>setAcceptLicense(e.target.checked)}/><span>Ich akzeptiere die <a href={corsair?.licenseUrl||'https://corsairofficial.github.io/cue-sdk/#end-user-license-agreement'} target="_blank" rel="noreferrer">Corsair-SDK-Lizenzbedingungen</a> für den Download der Anbindung.</span></label><button className="secondary wide" onClick={onSetup} disabled={busy||!acceptLicense}><Download size={17}/>{busy?'Bitte warten …':'Corsair-Anbindung einrichten'}</button></>}</section>
  {status.error?<div className="connection-error"><Info size={18}/><span>{status.error}</span></div>:null}
  <button className="primary wide" onClick={onConnect} disabled={busy}><Search size={17} className={busy?'spin':''}/>{busy?'Geräte werden gesucht …':'RGB-Geräte suchen'}</button>
  <p className="small muted">Stream Deck und Elgato-Geräte sind ausgeschlossen. PRISM erkennt verfügbare RGB-Geräte automatisch. Farben ändern sich erst mit „Auf Geräte anwenden“. Die Corsair-Anbindung wird nur nach deiner Zustimmung heruntergeladen.</p>
 </Modal>;
}
function DevicePage({devices,selected,toggle,preview,zoneIds,setZoneIds,system,onScan,busy,onRefresh,systemBusy,status,coverage,coverageBusy,coverageError,onCoverageRefresh}){
 const realDevices=preview?[]:devices;
 return <div className="page-content devices-page">
  <SystemInventory system={system} busy={systemBusy} onRefresh={onRefresh}/>
  <ManufacturerCoverage coverage={coverage} busy={coverageBusy} error={coverageError} onRefresh={onCoverageRefresh}/>
  <section className="rgb-device-section"><div className="page-intro"><div><h2>RGB-Geräte & Anbindungen</h2><p>{preview?'Die PC-Erkennung oben arbeitet unabhängig. Prüfe hier die RGB-Unterstützung deines PCs.':`${realDevices.length} RGB-Geräte mit Namen gemeldet. Verfügbare Beleuchtung und Einschränkungen werden pro Gerät angezeigt.`}</p></div><button className="secondary" onClick={onScan} disabled={busy}><Search size={17}/>{busy?'Suche läuft …':'RGB-Geräte suchen'}</button></div>
  <RGBDiscovery status={status}/><div className="device-list surface">{realDevices.length===0?<div className="empty"><Cpu size={36}/><h3>{preview?'RGB-Steuerung noch nicht verbunden':'Keine RGB-Geräte über diese Schnittstellen gefunden'}</h3><p>{preview?'Es wurde noch keine RGB-Verbindung aufgebaut. Die Lichtvorschau unter „Beleuchtung“ zeigt virtuelle Beispielgeräte.':'Die oben erkannten Komponenten bleiben verfügbar. RGB-RAM benötigt eine passende Hersteller-Anbindung; Windows kann nur kompatible Geräte steuern.'}</p>{status.message?<p>{status.message}</p>:null}<button className="primary" onClick={onScan} disabled={busy}><Search size={17}/>RGB-Unterstützung prüfen</button></div>:realDevices.map(d=><article key={d.id} className="device-detail"><div className="device-detail-top"><HardwareVisual type={d.category}/><div><h3>{d.name}</h3><p>{d.vendor||'Hersteller nicht gemeldet'} · {d.ledCount} LEDs</p><span className="device-provider">{providerName(d.provider||d.backend)}</span><span className={d.directMode?'support-status':'muted'}>{d.directMode?'Direkte LED-Steuerung verfügbar':'Keine direkte LED-Steuerung verfügbar'}</span></div><label className="device-use"><input type="checkbox" checked={selected.includes(d.id)} disabled={!d.directMode} onChange={()=>toggle(d.id)}/>Ausgewählt</label></div><div className="zone-row"><span>LED-Zonen</span>{d.zones.filter(z=>z.ledCount>0).map(z=><label key={z.id}><input type="checkbox" disabled={!d.directMode} checked={!zoneIds[d.id]||zoneIds[d.id].includes(z.id)} onChange={()=>setZoneIds(current=>{const all=d.zones.filter(z=>z.ledCount>0).map(z=>z.id);const values=current[d.id]||all;return {...current,[d.id]:values.includes(z.id)?values.filter(x=>x!==z.id):[...values,z.id]};})}/>{z.name} <small>{z.ledCount}</small></label>)}</div><ControllerChannels channels={d.channels}/>{d.location?<p className="device-location">{d.location}</p>:null}</article>)}</div></section>
 </div>;
}
function ProfilesPage({profiles,onLoad,onDelete,onSave,onImport}){const file=useRef(null);return <div className="page-content"><div className="page-intro"><div><h2>Deine Lichtprofile</h2><p>Speichere deine Einstellungen und nimm sie auf einen anderen PC mit.</p></div><div className="button-row"><button className="secondary" disabled={!profiles.length} onClick={()=>downloadProfiles(profiles)}><Download size={16}/>Exportieren</button><button className="secondary" onClick={()=>file.current.click()}><Upload size={16}/>Importieren</button><input ref={file} type="file" accept="application/json,.json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)onImport(f);e.target.value='';}}/></div></div><div className="profiles-list">{profiles.map(p=><article className="profile-item surface" key={p.id}><div className="profile-color" style={{background:`linear-gradient(120deg,${p.config.colors.join(',')})`}}/><div><h3>{p.name}</h3><p>{EFFECT_NAMES[p.config.effect]} · {p.config.brightness}% Helligkeit</p></div><div className="button-row"><button className="secondary" onClick={()=>onLoad(p)}><Play size={16}/>Laden</button><button className="icon-button" onClick={()=>onDelete(p.id)} aria-label={`Profil ${p.name} löschen`}><Trash2 size={18}/></button></div></article>)}</div>{!profiles.length?<div className="empty surface"><Folder size={40}/><h2>Platz für deinen Stil.</h2><p>Stelle dein Licht ein und speichere dein erstes Profil.</p><button className="primary" onClick={onSave}><Plus size={17}/>Profil speichern</button></div>:null}<Scenes onChoose={onLoad} active=""/></div>}

export default function App(){
 const [page,setPage]=useState('devices'),[config,setConfig]=useState(DEFAULT_CONFIG),[devices,setDevices]=useState([]),[preview,setPreview]=useState(true),[selected,setSelected]=useState(PREVIEW_DEVICES.map(d=>d.id)),[zoneIds,setZoneIds]=useState({}),[status,setStatus]=useState({connected:false,error:null}),[system,setSystem]=useState(null),[corsair,setCorsair]=useState(null),[systemBusy,setSystemBusy]=useState(true),[running,setRunning]=useState(true),[sync,setSync]=useState(true),[busy,setBusy]=useState(false),[modal,setModal]=useState(null),[profileName,setProfileName]=useState(''),[profiles,setProfiles]=useState(readProfiles),[toast,setToast]=useState(null),[activeScene,setActiveScene]=useState('');
 const controllableCount=devices.filter(d=>d.directMode).length;
 const visibleDevices=preview?PREVIEW_DEVICES:devices;const selectedDevices=visibleDevices.filter(d=>selected.includes(d.id)&&(!zoneIds[d.id]||zoneIds[d.id].length>0));
 const profileListRef=useRef(profiles);profileListRef.current=profiles;
 const startupDetectionRef=useRef(null);
 const [coverage,setCoverage]=useState(null),[coverageBusy,setCoverageBusy]=useState(true),[coverageError,setCoverageError]=useState(null);
 const coverageRequestRef=useRef(0),appAliveRef=useRef(true);
 const coverageStatusRef=useRef('');
 const liveCoverage=status.connected?coverage:inactiveCoverage(coverage);
 async function refreshCoverage(){const requestId=++coverageRequestRef.current;setCoverageBusy(true);try{const value=await api('coverage');if(appAliveRef.current&&requestId===coverageRequestRef.current){setCoverage(value);setCoverageError(null);}}catch(error){if(appAliveRef.current&&requestId===coverageRequestRef.current)setCoverageError(`Herstellerübersicht konnte nicht aktualisiert werden: ${error.message}`);}finally{if(appAliveRef.current&&requestId===coverageRequestRef.current)setCoverageBusy(false);}}
 useEffect(()=>{try{localStorage.setItem('prism.profiles.v1',JSON.stringify(profiles));}catch{setToast({type:'error',message:'Profile konnten nicht lokal gespeichert werden. Exportiere sie als Datei.'});}},[profiles]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),6000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{let alive=true;
  appAliveRef.current=true;void refreshCoverage();
  api('system').then(x=>{if(alive)setSystem(x);}).catch(e=>{if(alive)setSystem({error:`PC-Informationen konnten nicht geladen werden: ${e.message}`,source:'Lokaler PRISM-Server'});}).finally(()=>{if(alive)setSystemBusy(false);});
  api('corsair').then(x=>{if(alive)setCorsair(x);}).catch(()=>{});
  setBusy(true);
  if(!startupDetectionRef.current)startupDetectionRef.current=api('discover',{});
  startupDetectionRef.current.then(x=>{if(!alive)return;const list=x.devices.map(d=>({...d,category:categorize(d)}));setStatus(x.status);coverageStatusRef.current=coverageStatusSignature(x.status);setDevices(list);setPreview(false);setSelected(list.filter(d=>d.directMode).map(d=>d.id));setRunning(Boolean(x.status.effectRunning));const active=x.status.active?.[0]?.settings;if(active){try{setConfig(validConfig(active));}catch{}}}).catch(e=>{if(alive)setStatus({connected:false,error:`RGB-Erkennung fehlgeschlagen: ${e.message}`});}).finally(()=>{if(alive){setBusy(false);void refreshCoverage();}});
  return()=>{alive=false;appAliveRef.current=false;++coverageRequestRef.current;};
 },[]);
 useEffect(()=>{
  if(preview||!status.connected)return;
  let alive=true,pending=false;
  const poll=async()=>{if(pending)return;pending=true;try{
    const s=await api('status');if(!alive)return;setStatus(s);const coverageSignature=coverageStatusSignature(s);if(coverageSignature!==coverageStatusRef.current){coverageStatusRef.current=coverageSignature;void refreshCoverage();}
    if(!s.connected){setRunning(false);setDevices([]);setSelected([]);setZoneIds({});setToast({type:'error',message:'Die Hardware-Verbindung wurde getrennt. Prüfe die RGB-Anbindung und iCUE.'});return;}
    if(s.deviceCount!==devices.length){const x=await api('devices');if(!alive)return;const list=x.devices.map(d=>({...d,category:categorize(d)}));setDevices(list);setSelected([]);setZoneIds({});setRunning(false);setSync(false);setToast({type:'error',message:'Die Geräteliste wurde geändert. Bitte Geräte erneut suchen und auswählen.'});}
    if(s.error&&s.error!==status.error){setRunning(false);setToast({type:'error',message:s.error});}
  }catch{if(alive){setStatus(s=>({...s,connected:false,error:'Der lokale PRISM-Server ist nicht erreichbar.'}));setRunning(false);setDevices([]);setSelected([]);void refreshCoverage();setToast({type:'error',message:'Der lokale PRISM-Server ist nicht erreichbar.'});}}finally{pending=false;}};
  const id=setInterval(poll,5000);return()=>{alive=false;clearInterval(id);};
 },[preview,status.connected,status.error,devices.length]);
 const notify=(message,type='success')=>setToast({message,type});
 async function connect(){setBusy(true);try{const x=await api('rescan',{});const list=x.devices.map(d=>({...d,category:categorize(d)}));setDevices(list);setStatus(x.status);coverageStatusRef.current=coverageStatusSignature(x.status);setPreview(false);setRunning(false);setSync(true);setSelected(list.filter(d=>d.directMode).map(d=>d.id));setZoneIds({});setModal(null);notify(list.length?`${list.length} RGB-Geräte erkannt.`:(x.message||'Keine kompatiblen RGB-Geräte gefunden.'),list.length?'success':'error');}catch(e){setStatus(s=>({...s,connected:false,error:e.message}));setModal('connect');}finally{setBusy(false);void refreshCoverage();}}
 async function setupCorsair(){setBusy(true);try{await api('corsair/setup',{acceptLicense:true});setCorsair(await api('corsair'));await connect();}catch(e){setStatus(s=>({...s,error:e.message}));}finally{setBusy(false);}}
 async function showControlWindow(){setBusy(true);try{await api('window/show',{});notify('PRISM-Steuerfenster geöffnet. Windows-Geräte benötigen dieses Fenster im Vordergrund.');}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
 async function refreshSystem(){setSystemBusy(true);try{setSystem(await api('system/refresh',{}));notify('PC-Informationen wurden erneut gelesen.');}catch(e){notify(`PC-Abfrage fehlgeschlagen: ${e.message}`,'error');}finally{setSystemBusy(false);void refreshCoverage();}}

 function toggle(id){setSync(false);setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 function chooseScene(scene){setConfig(c=>({...c,...(scene.config||{effect:scene.effect,colors:scene.colors})}));setActiveScene(scene.name);setRunning(true);}
 async function apply(){if(!selectedDevices.length){notify('Bitte mindestens ein Gerät mit einer LED-Zone auswählen.','error');return;}setRunning(true);if(preview){notify('Lichtvorschau angewendet. Keine Hardware verbunden.');return;}setBusy(true);try{const x=await api('apply',{...config,deviceIds:selectedDevices.map(d=>d.id),zoneIds});notify(`Beleuchtung auf ${x.applied?.length??selected.length} Geräte angewendet.`);}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
 async function pause(){if(!preview){try{await api('stop',{});}catch(e){notify(e.message,'error');return;}}setRunning(r=>!r);if(!preview&&running)notify('Effekt gestoppt. Die letzte LED-Farbe bleibt erhalten.');if(!preview&&!running)await apply();}
 async function switchToPreview(){if(!preview&&status.connected){try{await api('stop',{});}catch(e){notify(e.message,'error');return;}}setPreview(true);setSelected(PREVIEW_DEVICES.map(d=>d.id));setZoneIds({});setRunning(true);setSync(true);notify('Vorschaumodus aktiv.');}
 async function blackout(){if(!preview){setBusy(true);try{await api('stop',{blackout:true,deviceIds:selected});}catch(e){notify(e.message,'error');return;}finally{setBusy(false);}}setConfig(c=>({...c,brightness:0}));notify(preview?'Vorschau ausgeschaltet.':'Ausgewählte Beleuchtung ausgeschaltet.');}
 function saveProfile(e){e.preventDefault();const name=profileName.trim();if(!name)return;if(profileListRef.current.length>=MAX_PROFILES){notify(`Maximal ${MAX_PROFILES} Profile. Lösche zuerst ein Profil.`,'error');return;}const next=[...profileListRef.current,{id:crypto.randomUUID(),name:name.slice(0,60),config:structuredClone(config)}];profileListRef.current=next;setProfiles(next);setModal(null);setProfileName('');notify(`„${name}“ gespeichert.`);}
 async function importProfiles(file){try{if(file.size>1024*1024)throw new Error('Die Profildatei ist zu groß (maximal 1 MB).');const data=JSON.parse(await file.text());if(!data||data.app!=='PRISM'||data.version!==1||!Array.isArray(data.profiles)||data.profiles.length>MAX_PROFILES)throw new Error('Das ist keine gültige PRISM-Profildatei.');const imported=data.profiles.map(p=>{if(!p||typeof p!=='object'||Array.isArray(p))throw new Error('Die Profildatei enthält ein ungültiges Profil.');return {id:crypto.randomUUID(),name:String(p.name||'Importiertes Profil').trim().slice(0,60)||'Importiertes Profil',config:validConfig(p.config)};});const slots=MAX_PROFILES-profileListRef.current.length;if(imported.length>slots)throw new Error(`Die Datei enthält ${imported.length} Profile. Es sind noch ${slots} Plätze frei (maximal ${MAX_PROFILES}). Lösche zuerst Profile; es wurde nichts importiert.`);if(!imported.length){notify('Die Datei enthält keine Profile.','error');return;}const next=[...profileListRef.current,...imported];profileListRef.current=next;setProfiles(next);notify(`${imported.length} Profile importiert.`);}catch(e){notify(e.message,'error');}}
 const openSave=()=>{if(profileListRef.current.length>=MAX_PROFILES){notify(`Maximal ${MAX_PROFILES} Profile. Lösche zuerst ein Profil.`,'error');return;}setProfileName(activeScene||'Mein Lichtprofil');setModal('save');};
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('lighting');}} aria-label="PRISM Start"><PrismLogo/><span>PRISM</span></a><nav aria-label="Hauptnavigation">{NAV.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)} aria-current={page===id?'page':undefined}><Icon size={22}/><span>{label}</span></button>)}</nav><div className="connection-card"><div><Monitor size={20}/><strong>{preview?'RGB noch nicht verbunden':status.connected?(controllableCount?'RGB verbunden':'Keine steuerbaren RGB-Geräte'):'RGB-Verbindung getrennt'}</strong></div><p>{preview?'Dein PC wird unabhängig erkannt':`${controllableCount} steuerbare RGB-Geräte · lokal`}</p><button className="outline" onClick={()=>setModal('connect')}><Link size={17}/>{!preview&&status.connected?'Geräte neu suchen':'RGB verbinden'}</button></div></aside><main><header className="page-header"><div><h1>{NAV.find(x=>x[0]===page)[1]}</h1><p>{page==='lighting'?'Dein Setup. Dein Licht.':page==='devices'?'Alles im Blick.':page==='profiles'?'Dein Licht. Gespeichert.':'Deine Steuerzentrale.'}</p></div><button className="outline save-button" onClick={openSave}><Save size={19}/><span>Profil speichern</span></button></header>
 {page==='lighting'?<>{preview?<div className="preview-explanation"><Info size={18}/><p>Virtuelle Lichtvorschau mit Beispielgeräten. Deine erkannten PC-Komponenten findest du unter „Geräte“.</p><button className="text-link" onClick={()=>setPage('devices')}>Deinen PC ansehen <ChevronRight size={14}/></button></div>:null}<DeviceSelector devices={visibleDevices} selected={selected} onToggle={toggle} preview={preview}/><div className="lighting-workspace"><div className="canvas-column"><section className="preview-panel surface"><div className="panel-heading"><h2>Setup-Vorschau</h2><div className="preview-actions"><label className="sync-label">Alle Geräte synchron<button role="switch" aria-label="Alle Geräte synchronisieren" aria-checked={sync} className={`switch ${sync?'on':''}`} onClick={()=>{const next=!sync;setSync(next);if(next){setSelected(visibleDevices.filter(d=>d.directMode).map(d=>d.id));setZoneIds({});}}}><span/></button></label><button className="icon-button playback" aria-label={running?'Vorschau pausieren':'Vorschau fortsetzen'} onClick={pause}>{running?<Pause size={16}/>:<Play size={16}/>}</button></div></div><PCPreview config={config} selectedTypes={selectedDevices.map(d=>d.category)} running={running} onSelectType={type=>{const match=visibleDevices.filter(d=>d.category===type&&d.directMode).map(d=>d.id);setSelected(match);setSync(false);}}/>{!preview?<div className="canvas-caption">Schematische Vorschau · {selectedDevices.length} echte Geräte ausgewählt</div>:null}</section><Scenes onChoose={chooseScene} active={activeScene}/></div><EffectEditor config={config} setConfig={c=>{setConfig(c);setActiveScene('');}} onApply={apply} onPreviewStart={()=>setRunning(true)} busy={busy} preview={preview} selectedCount={selectedDevices.length}/></div></>:null}
 {page==='devices'?<DevicePage devices={visibleDevices} selected={selected} toggle={toggle} preview={preview} zoneIds={zoneIds} setZoneIds={setZoneIds} system={system} onScan={()=>setModal('connect')} busy={busy} systemBusy={systemBusy} onRefresh={refreshSystem} status={status} coverage={liveCoverage} coverageBusy={coverageBusy} coverageError={coverageError} onCoverageRefresh={refreshCoverage}/>:null}
 {page==='profiles'?<ProfilesPage profiles={profiles} onLoad={p=>{chooseScene(p);setPage('lighting');notify(`„${p.name}“ geladen. Auf Geräte anwenden, um Hardware zu ändern.`);}} onDelete={id=>{setProfiles(p=>p.filter(x=>x.id!==id));notify('Profil gelöscht.');}} onSave={openSave} onImport={importProfiles}/>:null}
 {page==='settings'?<div className="page-content settings-page"><section className="surface settings-section"><h2>RGB-Anbindung ohne OpenRGB</h2><p>PRISM steuert kompatible Windows-Geräte und unterstützte Corsair-Geräte über iCUE. Die PC-Erkennung funktioniert unabhängig davon.</p><div className="setting-row"><span>Status</span><strong>{status.connected?(controllableCount?`${controllableCount} steuerbare RGB-Geräte`:'Anbindung bereit · keine steuerbaren Geräte'):'Noch nicht verbunden'}</strong></div><div className="setting-row"><span>Stream Deck & Elgato</span><strong>Von der RGB-Steuerung ausgeschlossen</strong></div><div className="button-row"><button className="primary" onClick={()=>setModal('connect')}><Link size={17}/>RGB-Anbindung öffnen</button><button className="secondary" onClick={switchToPreview}>Vorschaumodus verwenden</button></div><div className="help-note"><Info size={19}/><p>Windows unterstützt nur Geräte mit Dynamischer Beleuchtung. Corsair-Geräte benötigen iCUE, erlaubte SDK-Steuerung und die Corsair-Anbindung. Für andere Mainboards, RAM-Modelle und Controller fehlt noch eine Hersteller-Anbindung. PRISM liest keine Temperaturen aus.</p></div><a href="https://learn.microsoft.com/windows/apps/develop/devices-sensors/lighting-dynamic-lamparray" target="_blank" rel="noreferrer" className="text-link">Windows-RGB-Unterstützung ansehen <ExternalLink size={14}/></a></section><section className="surface settings-section"><h2>Lichtsteuerung</h2><p>Effekte werden lokal berechnet. Corsair-Effekte benötigen laufendes iCUE. Die Windows-Steuerung benötigt das PRISM-Steuerfenster im Vordergrund. Schließe das PRISM-Serverfenster zum Beenden.</p><button className="secondary" onClick={blackout} disabled={busy}><Power size={17}/>Beleuchtung ausschalten</button></section><section className="surface settings-section"><h2>Profile & Datenschutz</h2><p>Deine Profile liegen in diesem Browser. Exportiere sie vor einem Browserwechsel. Die Anwendung arbeitet lokal und benötigt kein Konto.</p><button className="secondary" onClick={()=>downloadProfiles(profiles)} disabled={!profiles.length}><Download size={17}/>Profile als Datei exportieren</button></section><p className="muted small">PRISM 1.4 · Lokale RGB-Steuerzentrale</p></div>:null}
 <footer className="statusbar"><span className={`status-dot ${!preview&&status.connected&&controllableCount?'connected':''}`}/><span>{preview?(page==='lighting'?'Virtuelle Lichtvorschau':'PC-Erkennung'):status.connected?(controllableCount?'RGB verbunden':'Keine steuerbaren RGB-Geräte'):'RGB-Verbindung getrennt'}</span><span className="dot-separator">·</span><span className="muted">{preview?(page==='lighting'?'Beispielgeräte':systemBusy?'PC wird ausgelesen':system?.error?'PC teilweise erkannt':'PC-Informationen gelesen'):`${selected.length} RGB-Geräte ausgewählt`}</span></footer></main>
 {modal==='connect'?<ConnectionDialog status={status} busy={busy} corsair={corsair} onConnect={connect} onSetup={setupCorsair} onShowWindow={showControlWindow} onClose={()=>setModal(null)}/>:null}
 {modal==='save'?<Modal title="Profil speichern" onClose={()=>setModal(null)}><form onSubmit={saveProfile}><p>Speichere Effekt, Farben und Feineinstellungen als eigenes Lichtprofil.</p><label className="form-label" htmlFor="profile-name">Profilname</label><input id="profile-name" className="text-input" autoComplete="off" value={profileName} maxLength={60} onChange={e=>setProfileName(e.target.value)} required/><div className="profile-summary"><span>{EFFECT_NAMES[config.effect]}</span><span>{config.brightness}% Helligkeit</span><div>{config.colors.map((c,i)=><i key={i} style={{background:c}}/>)}</div></div><button className="primary wide" type="submit" disabled={!profileName.trim()}><Save size={17}/>Profil speichern</button></form></Modal>:null}
 {toast?<div className={`toast ${toast.type}`} role="status">{toast.type==='error'?<Info size={19}/>:<CheckCircle2 size={19}/>}<span>{toast.message}</span><button onClick={()=>setToast(null)} aria-label="Meldung schließen"><X size={16}/></button></div>:null}
 </div>;
}
