import React,{useMemo,useState} from 'react';
import {Search,ShieldCheck,Usb,Monitor,Info,ChevronRight} from 'lucide-react';

const EMPTY=[];
const CATEGORIES={keyboard:'Tastaturen',mouse:'Mäuse',audio:'Audio',monitor:'Monitore',network:'Netzwerk',bluetooth:'Bluetooth',camera:'Kameras',printer:'Drucker',usb:'USB-Geräte',controller:'Controller',peripheral:'Weitere Geräte',system:'Systemgeräte',storage:'Laufwerke',processor:'Prozessoren',memory:'Arbeitsspeicher',gpu:'Grafikkarten'};
const statusText=status=>status==='OK'?'Bereit':status==='Error'?'Windows meldet ein Problem':status==='Degraded'?'Eingeschränkt':status==='Unknown'?'Status unbekannt':status||'Status nicht gemeldet';

export function HardwareDevices({system}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[showProtected,setShowProtected]=useState(false);
 const allDevices=system?.devices||system?.peripherals||EMPTY;
 const monitors=system?.monitors||EMPTY;
 const deviceError=(system?.errors||EMPTY).find(e=>['devices','peripherals','pnp'].includes(e.component));
 const categories=useMemo(()=>{const counts=new Map();for(const device of allDevices){const key=device.category||'peripheral';counts.set(key,(counts.get(key)||0)+1);}return [...counts].sort(([a],[b])=>(CATEGORIES[a]||a).localeCompare(CATEGORIES[b]||b,'de-DE'));},[allDevices]);
 const filtered=useMemo(()=>{const text=query.trim().toLocaleLowerCase('de-DE');return allDevices.filter(device=>(category==='all'||(device.category||'peripheral')===category)&&(!showProtected||device.protected)&&(!text||[device.name,device.manufacturer,device.instanceId,device.connection,device.className||device.deviceClass].filter(Boolean).join(' ').toLocaleLowerCase('de-DE').includes(text)));},[allDevices,category,showProtected,query]);
 const protectedCount=allDevices.filter(device=>device.protected).length;
 return <section className="hardware-explorer" aria-labelledby="hardware-explorer-title">
  <div className="page-intro"><div><h2 id="hardware-explorer-title">Windows-Geräte mit Namen</h2><p>Vorhandene Windows-Geräteeinträge mit ihren gemeldeten Namen und Anbietern. Dazu zählen auch Schnittstellen und Softwaregeräte; mehrere Einträge können zum selben Gerät gehören.</p></div><span className="hardware-total">{allDevices.length} Windows-Einträge</span></div>
  {monitors.length?<div className="monitor-names surface"><Monitor size={20}/><div><strong>Angeschlossene Monitore</strong>{monitors.map((monitor,i)=><span key={monitor.instanceId||i}>{monitor.name||'Name nicht vom Monitor gemeldet'}{monitor.manufacturer?` · ${monitor.manufacturer}`:''}</span>)}</div></div>:null}
  <div className="hardware-searchbar"><label className="hardware-search"><Search size={18}/><input type="search" aria-label="Windows-Geräte suchen" placeholder="Name, Hersteller oder Gerätekennung suchen …" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="hardware-filter"><span>Geräteart</span><select aria-label="Windows-Geräte nach Art filtern" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Alle Geräte ({allDevices.length})</option>{categories.map(([key,count])=><option key={key} value={key}>{CATEGORIES[key]||key} ({count})</option>)}</select></label></div>
  <div className="hardware-results-heading"><p role="status">{filtered.length} von {allDevices.length} Windows-Einträgen{query.trim()?` für „${query.trim()}“`:''}</p>{protectedCount?<label className="protected-filter"><input type="checkbox" checked={showProtected} onChange={e=>setShowProtected(e.target.checked)}/>Nur geschützte Einträge ({protectedCount})</label>:null}</div>
  <div className="hardware-results surface" tabIndex={0} aria-label="Liste der von Windows erkannten Geräte">{filtered.length?filtered.map((device,index)=><article className="hardware-item" key={device.id||device.instanceId||index}>
   <div className="hardware-item-name"><Usb size={19}/><div><h3>{device.name||'Windows hat keinen Gerätenamen gemeldet'}</h3><p>{[device.manufacturer,CATEGORIES[device.category]||'Weitere Geräte',device.connection].filter(Boolean).join(' · ')}</p></div></div>
   <div className="hardware-item-state"><span className={`hardware-windows-status ${device.status==='Error'?'problem':''}`}>{statusText(device.status)}</span><span className={`hardware-rgb-status ${device.protected?'protected':''}`}>{device.protected?<><ShieldCheck size={13}/>Nur Anzeige · RGB ausgeschlossen</>:'Erkannt · RGB separat prüfen'}</span></div>
   <details className="hardware-details"><summary>Gerätedetails <ChevronRight size={12}/></summary><dl><div><dt>Gerätekennung</dt><dd>{device.instanceId||device.id||'Nicht gemeldet'}</dd></div><div><dt>Windows-Geräteklasse</dt><dd>{device.className||device.deviceClass||'Nicht gemeldet'}</dd></div><div><dt>Erkennung</dt><dd>{device.source||'Windows'}</dd></div></dl>{device.protected?<p>PRISM zeigt dieses Gerät nur an. Es ist für die RGB-Steuerung gesperrt.</p>:<p>Ein Eintrag in Windows bestätigt die Geräteerkennung. Eine verfügbare RGB-Anbindung wird unten separat angezeigt.</p>}</details>
  </article>):<div className="empty hardware-empty"><Search size={29}/><h3>{allDevices.length?'Keine passenden Geräte':'Windows hat keine Geräteinformationen geliefert'}</h3><p>{allDevices.length?'Ändere den Suchbegriff oder den Filter.':deviceError?.message||'Erkenne den PC erneut, um die Windows-Geräteliste zu laden.'}</p>{query||category!=='all'||showProtected?<button className="secondary" onClick={()=>{setQuery('');setCategory('all');setShowProtected(false);}}>Suche und Filter zurücksetzen</button>:null}</div>}</div>
  <div className="inventory-boundary"><Info size={18}/><p>Lüfter und LED-Bänder an einem Mainboard-Header oder Hub melden oft keinen eigenen Modellnamen. Windows kann dann nur den gemeinsamen Controller erkennen. Geräte mit verfügbaren RGB-Anbindungen stehen in der separaten Lichtsteuerung.</p></div>
 </section>;
}
