import test from 'node:test';
import assert from 'node:assert/strict';
import { EFFECTS, renderFrame, validateSettings } from '../server/effects.mjs';
import { createEffectSampler } from '../src/effect-color.js';

const added = ['colorcycle', 'comet', 'chase', 'scanner', 'ripple', 'fire', 'aurora', 'stripes'];
const config = (effect, overrides = {}) => validateSettings({ effect, colors: ['#ff0000', '#00ff00', '#0000ff'], brightness: 100, speed: 50, scale: 40, ...overrides });
const velocity = settings => 0.05 + settings.speed / 100 * 1.8;
const atPhase = (count, settings, phase) => renderFrame(count, settings, phase / velocity(settings));
const channels = packed => [packed & 255, (packed >>> 8) & 255, (packed >>> 16) & 255];
const light = packed => channels(packed).reduce((sum, channel) => sum + channel, 0);
const peak = frame => frame.indexOf(Math.max(...frame));
const transitions = frame => frame.slice(1).filter((color, index) => color !== frame[index]).length;

test('all fourteen effects are accepted with the same editable settings', () => {
  assert.equal(EFFECTS.length, 14);
  assert.equal(new Set(EFFECTS).size, 14);
  for (const effect of EFFECTS) assert.equal(config(effect).effect, effect);
  assert.throws(() => config('missing-effect'), { code: 'INVALID_EFFECT' });
  assert.throws(() => config('fire', { colors: [] }), { code: 'INVALID_COLORS' });
  assert.throws(() => config('fire', { colors: Array(9).fill('#ff0000') }), { code: 'INVALID_COLORS' });
});

test('the original six effects preserve captured LED frames in both directions', () => {
  // Captured from the original 1.3 renderer before consolidation, not generated by this implementation.
  const snapshots = {
    static: [[6100911,6100911,6100911,6100911,6100911,6100911,6100911], [6100911,6100911,6100911,6100911,6100911,6100911,6100911]],
    rainbow: [[9419264,12189836,35258,8829440,12189827,33210,8305152], [12226304,9502906,47764,12228352,10092730,47773,12230400]],
    breathing: [[6035373,8011893,10054205,12030726,8821523,5612321,2468655], [6035373,8011893,10054205,12030726,8821523,5612321,2468655]],
    wave: [[2037513,6763121,2128673,2037511,6499955,2260513,2103302], [1908227,4395894,4821791,1842948,4264564,5149726,1843204]],
    gradient: [[6100911,8143223,10185534,12162310,8953108,5743906,2469423], [2469423,5743906,8953108,12162310,10185534,8143223,6100911]],
    sparkle: [[66817,196869,394240,196869,394240,394240,6100911], [66817,196869,394240,196869,394240,394240,6100911]]
  };
  for (const [effect, directions] of Object.entries(snapshots)) {
    for (const [index, direction] of ['forward', 'reverse'].entries()) {
      const settings = config(effect, { colors: ['#f02080','#08ccfe','#41ee33'], brightness: 73, speed: 63, scale: 27, direction });
      assert.deepEqual(renderFrame(7, settings, 1.234), directions[index], `${effect}/${direction}`);
    }
  }
});

test('every effect handles empty and single LED devices, palette limits, and zero brightness', () => {
  const palettes = [['#000000'], ['#000000','#ffffff','#ff0000','#00ff00','#0000ff','#00ffff','#ff00ff','#ffff00']];
  for (const effect of EFFECTS) for (const colors of palettes) for (const edge of [1, 100]) {
    const settings = config(effect, { colors, speed: edge, scale: edge, direction: 'reverse' });
    assert.deepEqual(renderFrame(0, settings, 499), []);
    for (const count of [1, 97]) for (const time of [0, 0.51, 499]) {
      const frame = renderFrame(count, settings, time);
      assert.equal(frame.length, count);
      assert.ok(frame.every(color => Number.isInteger(color) && color >= 0 && color <= 0xffffff), effect);
      assert.ok(renderFrame(count, { ...settings, brightness: 0 }, time).every(color => color === 0), effect);
    }
  }
});

test('browser preview samples match the hardware RGB frame including brightness rounding', () => {
  for (const effect of EFFECTS) for (const direction of ['forward', 'reverse']) {
    const settings = config(effect, { direction, brightness: 37, colors: ['#812bd1', '#c40aff', '#40e9bc'], speed: 17, scale: 83 });
    const frame = renderFrame(23, settings, 1.37), sample = createEffectSampler(settings, 1.37);
    for (let index = 0; index < frame.length; index++) {
      const { color, alpha } = sample(index / (frame.length - 1), index);
      assert.ok(alpha >= 0 && alpha <= 1);
      assert.deepEqual(channels(frame[index]), color.map(value => Math.round(value * alpha)), `${effect}/${direction}/${index}`);
    }
  }
  assert.equal(createEffectSampler({}, 0)(0).alpha, 0.8, 'preview retains default brightness');
});

test('colorcycle blends the chosen palette uniformly and closes the color loop', () => {
  const settings = config('colorcycle', { colors: ['#ff0000', '#00ff00'] });
  const initial = atPhase(31, settings, 0), middle = atPhase(31, settings, 0.25), second = atPhase(31, settings, 0.5);
  assert.ok(initial.every(color => color === 0x0000ff));
  assert.ok(middle.every(color => color === 0x008080));
  assert.ok(second.every(color => color === 0x00ff00));
  assert.deepEqual(atPhase(31, settings, 1), initial);
  assert.deepEqual(atPhase(31, { ...settings, scale: 100 }, 0.25), middle);
});

test('comet moves its bright head, leaves a tail behind, and changes tail length', () => {
  const settings = config('comet', { colors: ['#ffffff'] });
  const first = atPhase(101, settings, 0.3), later = atPhase(101, settings, 0.6);
  assert.equal(peak(first), 30);
  assert.equal(peak(later), 60);
  assert.ok(light(first[20]) > light(first[40]), 'tail follows rather than precedes the head');
  assert.deepEqual(atPhase(101, { ...settings, direction: 'reverse' }, 0.3), first.toReversed());
  const narrow = atPhase(101, { ...settings, scale: 1 }, 0.5), wide = atPhase(101, { ...settings, scale: 100 }, 0.5);
  assert.ok(wide.filter(color => light(color) > 100).length > narrow.filter(color => light(color) > 100).length);
});

test('chase carries separated lights along the strip and scale controls repetition', () => {
  const settings = config('chase', { colors: ['#ffffff'], scale: 100 * 0.5 / 5.5 });
  const first = atPhase(101, settings, 0.1), later = atPhase(101, settings, 0.3);
  assert.equal(peak(first), 24);
  assert.equal(peak(later), 44);
  assert.ok(light(first[24]) > light(first[64]) * 10);
  assert.deepEqual(atPhase(101, { ...settings, direction: 'reverse' }, 0.1), first.toReversed());
  assert.notDeepEqual(atPhase(101, { ...settings, scale: 100 }, 0.1), first);
});

test('scanner reaches both endpoints, turns around, and honors beam width and start direction', () => {
  const settings = config('scanner', { colors: ['#ffffff'] });
  assert.deepEqual([0, 0.5, 1, 1.5, 2].map(phase => peak(atPhase(101, settings, phase))), [0, 50, 100, 50, 0]);
  assert.equal(peak(atPhase(101, { ...settings, direction: 'reverse' }, 0.25)), 75);
  const narrow = atPhase(101, { ...settings, scale: 1 }, 0.5), wide = atPhase(101, { ...settings, scale: 100 }, 0.5);
  assert.ok(wide.filter(color => light(color) > 100).length > narrow.filter(color => light(color) > 100).length);
});

test('ripple remains symmetric about the center while waves move in either direction', () => {
  const settings = config('ripple');
  const frame = atPhase(101, settings, 0.23);
  assert.deepEqual(frame, frame.toReversed());
  assert.notDeepEqual(atPhase(101, settings, 0.44), frame);
  assert.notDeepEqual(atPhase(101, { ...settings, direction: 'reverse' }, 0.23), frame);
  assert.notDeepEqual(atPhase(101, { ...settings, scale: 1 }, 0.23), frame);
});

test('stripes use only selected colors, move, reverse, and become denser with scale', () => {
  const settings = config('stripes'), colors = new Set([0x0000ff, 0x00ff00, 0xff0000]);
  const frame = atPhase(151, settings, 0.37);
  assert.ok(frame.every(color => colors.has(color)));
  assert.deepEqual(new Set(frame), colors);
  assert.notDeepEqual(atPhase(151, settings, 0.5), frame);
  assert.deepEqual(atPhase(151, { ...settings, direction: 'reverse' }, 0.37), frame.toReversed());
  assert.ok(transitions(atPhase(151, { ...settings, scale: 100 }, 0.37)) > transitions(atPhase(151, { ...settings, scale: 1 }, 0.37)));
});

test('fire is deterministic, changes smoothly, and honors a custom non-fire palette', () => {
  const settings = config('fire', { colors: ['#000030', '#0000ff'] });
  const frame = renderFrame(97, settings, 2.345), next = renderFrame(97, settings, 2.3451);
  assert.deepEqual(renderFrame(97, settings, 2.345), frame);
  assert.ok(frame.every(color => (color & 0xffff) === 0), 'a blue palette never produces hardcoded orange or red');
  assert.ok(frame.some(color => color !== frame[0]), 'flame structure varies along the strip');
  assert.ok(next.every((color, index) => Math.abs(channels(color)[2] - channels(frame[index])[2]) <= 1), 'small time steps have no random flashes');
  assert.notDeepEqual(renderFrame(97, settings, 3.345), frame);
  assert.notDeepEqual(renderFrame(97, { ...settings, scale: 1 }, 2.345), frame);
  assert.deepEqual(renderFrame(97, { ...settings, direction: 'reverse' }, 2.345), frame.toReversed());
});

test('aurora layers the chosen colors into animated bands and responds to scale and direction', () => {
  const settings = config('aurora', { colors: ['#000030', '#0000ff'] });
  const frame = renderFrame(97, settings, 1.71);
  assert.ok(frame.every(color => (color & 0xffff) === 0));
  assert.ok(frame.some(color => color !== frame[0]));
  assert.notDeepEqual(renderFrame(97, settings, 2.3), frame);
  assert.notDeepEqual(renderFrame(97, { ...settings, scale: 1 }, 1.71), frame);
  assert.deepEqual(renderFrame(97, { ...settings, direction: 'reverse' }, 1.71), frame.toReversed());
});

test('speed advances all eight new effects while identical phases retain identical frames', () => {
  for (const effect of added) {
    const slow = config(effect, { speed: 1 }), fast = config(effect, { speed: 100 });
    assert.notDeepEqual(renderFrame(97, fast, 0.51), renderFrame(97, slow, 0.51), effect);
    assert.deepEqual(atPhase(97, fast, 0.371), atPhase(97, slow, 0.371), effect);
  }
});
